capitulos:
  "01": "Replanteo"
  "02": "Movimiento de tierras"
  "03": "Hormigones"
  "04": "Acero estructural"
  "05": "Mampostería"
  "06": "Enlucidos y masillados"
  "07": "Impermeabilización"
  "08": "Acabados"
  "09": "Carpintería"
  "10": "Instalaciones eléctricas"
  "11": "Instalaciones hidrosanitarias"
  "12": "Instalaciones especiales"
  "13": "Equipamiento"
  "14": "Obras exteriores"
  "31": "Obras complementarias"
  "41": "Elementos varios"
